import{r as i,j as e}from"./jsx-runtime.js";import{l as d,n as f,o as g,p as x,_ as y,O as S,M as j,L as w,S as k}from"./components.js";/**
 * @remix-run/react v2.15.3
 *
 * Copyright (c) Remix Software Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */let l="positions";function b({getKey:t,...a}){let{isSpaMode:c}=d(),n=f(),p=g();x({getKey:t,storageKey:l});let u=i.useMemo(()=>{if(!t)return null;let s=t(n,p);return s!==n.key?s:null},[]);if(c)return null;let m=((s,h)=>{if(!window.history.state||!window.history.state.key){let o=Math.random().toString(32).slice(2);window.history.replaceState({key:o},"")}try{let r=JSON.parse(sessionStorage.getItem(s)||"{}")[h||window.history.state.key];typeof r=="number"&&window.scrollTo(0,r)}catch(o){console.error(o),sessionStorage.removeItem(s)}}).toString();return i.createElement("script",y({},a,{suppressHydrationWarning:!0,dangerouslySetInnerHTML:{__html:`(${m})(${JSON.stringify(l)}, ${JSON.stringify(u)})`}}))}const z=()=>[{title:"👨‍💻 Angel Gonzalez | FullStack Web Developer"},{name:"description",content:"Hi! I'm Angel Gonzalez, a passionate FullStack Web Developer focused on creating elegant and efficient web solutions."}];function O({children:t}){return e.jsxs("html",{lang:"en",children:[e.jsxs("head",{children:[e.jsx("meta",{charSet:"utf-8"}),e.jsx("meta",{name:"viewport",content:"width=device-width, initial-scale=1"}),e.jsx("link",{rel:"preconnect",href:"https://fonts.googleapis.com"}),e.jsx("link",{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"}),e.jsx("link",{href:"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap",rel:"stylesheet"}),e.jsx("title",{children:"👨‍💻 Angel Gonzalez | FullStack Web Developer"}),e.jsx(j,{}),e.jsx(w,{})]}),e.jsxs("body",{className:"font-roboto",children:[t,e.jsx(b,{}),e.jsx(k,{})]})]})}function L(){return e.jsx(S,{})}export{O as Layout,L as default,z as meta};
